// games/questions/questionsList.js
module.exports = [
  "Who is most likely to cry during a movie?",
  "Who is most likely to survive a zombie apocalypse?",
  "Who tells the worst jokes?",
  "Who’s the loudest after one drink?",
  "Who has the strangest party story?",
  "Who forgets people’s names the fastest?",
  "Who’s most likely to drunk-text an ex?",
  "Who is the most competitive?",
  "Who’s most likely to get kicked out of a bar?",
  "Who takes the longest to reply in group chats?",
  "Who always shows up late?",
  "Who is the most likely to order shots for the table?",
  "Who laughs at their own jokes the most?",
  "Who’s most likely to fall asleep during a party?",
  "Who would win a dance battle?",
  "Who would be the best reality TV star?",
  "Who can’t keep a secret?",
  "Who’s the most spontaneous?",
  "Who’s most likely to get lost on a road trip?",
  "Who gives the best advice?",
  "Who’s most likely to break something while drunk?",
  "Who’s most likely to make a dramatic exit?",
  "Who is the worst at keeping plans?",
  "Who is most likely to start a group karaoke session?",
  "Who’s the best storyteller?",
  "Who’s most likely to cry while laughing?",
  "Who’s the sneakiest?",
  "Who’s most likely to accidentally double-text?",
  "Who has the most unique laugh?",
  "Who’s most likely to ghost a group chat?",
  "Who’s most likely to prank someone?",
  "Who would survive the longest on a deserted island?",
  "Who’s most likely to forget why they walked into a room?",
  "Who can’t resist taking selfies?",
  "Who’s most likely to dance without music?",
  "Who overuses emojis?",
  "Who is the pickiest eater?",
  "Who has the weirdest phobia?",
  "Who is the most likely to win an Oscar?",
  "Who would get a tattoo on a dare?",
  "Who’s the best at impressions?",
  "Who gets the most excited about plans?",
  "Who would make the best stand-up comedian?",
  "Who’s the most sarcastic?",
  "Who’s the most dramatic texter?",
  "Who’s the most likely to cry during arguments?",
  "Who’s most likely to spill a secret?",
  "Who’s most likely to befriend a stranger at a bar?",
  "Who’s most likely to be the DJ at a party?",
  "Who has the worst handwriting?",
  "Who’s the most stylish?",
  "Who has the best resting face?",
  "Who’s the most organized?",
  "Who’s the most forgetful?",
  "Who always knows the latest gossip?",
  "Who gives the most backhanded compliments?",
  "Who’s the most likely to get caught singing in the shower?",
  "Who’s most likely to go viral accidentally?",
  "Who’s the most likely to trip while walking?",
  "Who’s the most likely to lock themselves out?",
  "Who’s the most likely to binge-watch a series in one day?",
  "Who would be the first to die in a horror movie?",
  "Who’s the most likely to own a weird pet?",
  "Who’s most likely to join a cult without realizing?",
  "Who’s the most likely to try a weird food first?",
  "Who’s the best hype-person?",
  "Who’s most likely to post a cringey throwback?",
  "Who’s the best at keeping calm in chaos?",
  "Who’s most likely to wear socks with sandals?",
  "Who gives the best hugs?",
  "Who’s most likely to become famous?",
  "Who’s most likely to start crying from laughter?",
  "Who’s most likely to cause a scene in public?",
  "Who’s the most photogenic?",
  "Who’s most likely to become a millionaire?",
  "Who’s most likely to text their crush something awkward?",
  "Who has the most surprising talent?",
  "Who’s most likely to scream during a horror film?",
  "Who’s most likely to forget their wallet?",
  "Who’s most likely to bring snacks everywhere?",
  "Who’s most likely to have a secret TikTok account?",
  "Who would survive the longest without their phone?",
  "Who’s most likely to laugh at the wrong moment?",
  "Who’s the worst at telling stories?",
  "Who’s most likely to go on a reality TV show?",
  "Who’s the best at coming up with dares?",
  "Who’s most likely to make a meme out of their own life?",
  "Who’s most likely to start a conspiracy theory?",
  "Who would get away with murder?",
  "Who’s the most unpredictable?",
  "Who has the most iconic catchphrase?",
  "Who’s most likely to become a meme?",
  "Who’s most likely to fall in love at first sight?",
  "Who’s most likely to cry at a commercial?",
  "Who’s the sassiest?",
  "Who would be voted class clown?",
  "Who would make the best detective?",
];

